# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 631)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 520, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lbl_model = QtWidgets.QLabel(self.centralWidget)
        self.lbl_model.setGeometry(QtCore.QRect(550, 50, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_model.setFont(font)
        self.lbl_model.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_model.setObjectName("lbl_model")
        self.lbl_rsqr = QtWidgets.QLabel(self.centralWidget)
        self.lbl_rsqr.setGeometry(QtCore.QRect(600, 100, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_rsqr.setFont(font)
        self.lbl_rsqr.setText("")
        self.lbl_rsqr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_rsqr.setObjectName("lbl_rsqr")
        self.lbl_lblRsqr = QtWidgets.QLabel(self.centralWidget)
        self.lbl_lblRsqr.setGeometry(QtCore.QRect(550, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lblRsqr.setFont(font)
        self.lbl_lblRsqr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lblRsqr.setObjectName("lbl_lblRsqr")
        self.lbl_rsqr_2 = QtWidgets.QLabel(self.centralWidget)
        self.lbl_rsqr_2.setGeometry(QtCore.QRect(690, 80, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(18)
        self.lbl_rsqr_2.setFont(font)
        self.lbl_rsqr_2.setText("")
        self.lbl_rsqr_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_rsqr_2.setObjectName("lbl_rsqr_2")
        self.txt_predict = QtWidgets.QLineEdit(self.centralWidget)
        self.txt_predict.setGeometry(QtCore.QRect(20, 542, 111, 24))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(14)
        self.txt_predict.setFont(font)
        self.txt_predict.setObjectName("txt_predict")
        self.btn_predict = QtWidgets.QPushButton(self.centralWidget)
        self.btn_predict.setGeometry(QtCore.QRect(140, 540, 131, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_predict.setFont(font)
        self.btn_predict.setObjectName("btn_predict")
        self.lbl_predict = QtWidgets.QLabel(self.centralWidget)
        self.lbl_predict.setGeometry(QtCore.QRect(280, 545, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(14)
        self.lbl_predict.setFont(font)
        self.lbl_predict.setText("")
        self.lbl_predict.setObjectName("lbl_predict")
        self.btn_fitModel = QtWidgets.QPushButton(self.centralWidget)
        self.btn_fitModel.setGeometry(QtCore.QRect(10, 490, 131, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_fitModel.setFont(font)
        self.btn_fitModel.setObjectName("btn_fitModel")
        self.btn_plot = QtWidgets.QPushButton(self.centralWidget)
        self.btn_plot.setGeometry(QtCore.QRect(140, 490, 131, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_plot.setFont(font)
        self.btn_plot.setObjectName("btn_plot")
        self.btn_clear = QtWidgets.QPushButton(self.centralWidget)
        self.btn_clear.setGeometry(QtCore.QRect(270, 490, 131, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_exit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_exit.setGeometry(QtCore.QRect(400, 490, 131, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 833, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Regrezio"))
        self.lbl_model.setText(_translate("MainWindow", "ŷ = "))
        self.lbl_lblRsqr.setText(_translate("MainWindow", "r^2 :"))
        self.txt_predict.setPlaceholderText(_translate("MainWindow", " Value"))
        self.btn_predict.setText(_translate("MainWindow", "Predict"))
        self.btn_fitModel.setText(_translate("MainWindow", "Fit the Model"))
        self.btn_plot.setText(_translate("MainWindow", "Show Plot"))
        self.btn_clear.setText(_translate("MainWindow", "Clear Values"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

