# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 624)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 520, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lbl_model = QtWidgets.QLabel(self.centralWidget)
        self.lbl_model.setGeometry(QtCore.QRect(130, 560, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_model.setFont(font)
        self.lbl_model.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_model.setObjectName("lbl_model")
        self.lbl_lblRsqr = QtWidgets.QLabel(self.centralWidget)
        self.lbl_lblRsqr.setGeometry(QtCore.QRect(370, 526, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lblRsqr.setFont(font)
        self.lbl_lblRsqr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lblRsqr.setObjectName("lbl_lblRsqr")
        self.lbl_rsqr = QtWidgets.QLabel(self.centralWidget)
        self.lbl_rsqr.setGeometry(QtCore.QRect(420, 526, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(16)
        self.lbl_rsqr.setFont(font)
        self.lbl_rsqr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_rsqr.setObjectName("lbl_rsqr")
        self.txt_predict = QtWidgets.QLineEdit(self.centralWidget)
        self.txt_predict.setGeometry(QtCore.QRect(20, 524, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(14)
        self.txt_predict.setFont(font)
        self.txt_predict.setObjectName("txt_predict")
        self.btn_predict = QtWidgets.QPushButton(self.centralWidget)
        self.btn_predict.setGeometry(QtCore.QRect(120, 520, 81, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_predict.setFont(font)
        self.btn_predict.setObjectName("btn_predict")
        self.lbl_predict = QtWidgets.QLabel(self.centralWidget)
        self.lbl_predict.setGeometry(QtCore.QRect(210, 526, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Palatino")
        font.setPointSize(16)
        self.lbl_predict.setFont(font)
        self.lbl_predict.setObjectName("lbl_predict")
        self.btn_fitModel = QtWidgets.QPushButton(self.centralWidget)
        self.btn_fitModel.setGeometry(QtCore.QRect(10, 480, 121, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_fitModel.setFont(font)
        self.btn_fitModel.setObjectName("btn_fitModel")
        self.btn_plot = QtWidgets.QPushButton(self.centralWidget)
        self.btn_plot.setGeometry(QtCore.QRect(230, 480, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_plot.setFont(font)
        self.btn_plot.setObjectName("btn_plot")
        self.btn_clear = QtWidgets.QPushButton(self.centralWidget)
        self.btn_clear.setGeometry(QtCore.QRect(340, 480, 101, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_exit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_exit.setGeometry(QtCore.QRect(440, 480, 91, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.cb_funcType = QtWidgets.QComboBox(self.centralWidget)
        self.cb_funcType.setGeometry(QtCore.QRect(130, 482, 101, 26))
        self.cb_funcType.setObjectName("cb_funcType")
        self.cb_funcType.addItem("")
        self.cb_funcType.addItem("")
        self.cb_funcType.addItem("")
        self.cb_funcType.addItem("")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 540, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTests = QtWidgets.QMenu(self.menuHelp)
        self.menuTests.setObjectName("menuTests")
        self.menuHelp_2 = QtWidgets.QMenu(self.menuBar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_CSV = QtWidgets.QAction(MainWindow)
        self.actionLoad_CSV.setObjectName("actionLoad_CSV")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionMWD = QtWidgets.QAction(MainWindow)
        self.actionMWD.setObjectName("actionMWD")
        self.actionLagrange_Multiplier = QtWidgets.QAction(MainWindow)
        self.actionLagrange_Multiplier.setObjectName("actionLagrange_Multiplier")
        self.actionBug_Report = QtWidgets.QAction(MainWindow)
        self.actionBug_Report.setObjectName("actionBug_Report")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionChow = QtWidgets.QAction(MainWindow)
        self.actionChow.setObjectName("actionChow")
        self.menuFile.addAction(self.actionLoad_CSV)
        self.menuTests.addAction(self.actionMWD)
        self.menuTests.addAction(self.actionLagrange_Multiplier)
        self.menuTests.addAction(self.actionChow)
        self.menuHelp.addAction(self.menuTests.menuAction())
        self.menuHelp_2.addAction(self.actionAbout_2)
        self.menuHelp_2.addAction(self.actionBug_Report)
        self.menuHelp_2.addAction(self.actionDocumentation)
        self.menuHelp_2.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jordamach"))
        self.lbl_model.setText(_translate("MainWindow", "ŷ = β0 + β1*X1 + ... + βnXn"))
        self.lbl_lblRsqr.setText(_translate("MainWindow", "r^2 :"))
        self.lbl_rsqr.setText(_translate("MainWindow", "0"))
        self.txt_predict.setPlaceholderText(_translate("MainWindow", " Value"))
        self.btn_predict.setText(_translate("MainWindow", "Predict"))
        self.lbl_predict.setText(_translate("MainWindow", "0"))
        self.btn_fitModel.setText(_translate("MainWindow", "Fit the Model"))
        self.btn_plot.setText(_translate("MainWindow", "Show Plot"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.cb_funcType.setItemText(0, _translate("MainWindow", "Lin-Lin"))
        self.cb_funcType.setItemText(1, _translate("MainWindow", "Lin-Log"))
        self.cb_funcType.setItemText(2, _translate("MainWindow", "Log-Lin"))
        self.cb_funcType.setItemText(3, _translate("MainWindow", "Log-Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Analyze"))
        self.menuTests.setTitle(_translate("MainWindow", "Tests"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad_CSV.setText(_translate("MainWindow", "Load CSV..."))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        self.actionMWD.setText(_translate("MainWindow", "MWD"))
        self.actionLagrange_Multiplier.setText(_translate("MainWindow", "Lagrange Multiplier"))
        self.actionBug_Report.setText(_translate("MainWindow", "Bug Report"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionChow.setText(_translate("MainWindow", "Chow"))

